// Login
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "strategy": "local",
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("token", response.body.accessToken); %}
###

// List tables
GET http://localhost:3030/tables
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

// Create table
POST http://localhost:3030/tables
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
}

> {%
  // client.log(response.body._id)
  client.global.set("tableId", response.body._id);
%}
###

// Patch table
PATCH http://localhost:3030/tables/{{tableId}}
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "_id": "{{tableId}}"
}
###
