// List tables
GET http://localhost:3030/tables
Accept: application/json
Content-Type: application/json
###

// Create table
POST http://localhost:3030/tables
Accept: application/json
Content-Type: application/json

{
  "list": [
    {
      "_id": "64b806da03ac5093de3f3e78",
      "name": "Test",
      "methods": [
        "get",
        "find"
      ],
      "created": true,
      "updated": true,
      "softDelete": true,
      "user": true,
      "fields": [
        {
          "_id": "64affb4f2a4bb338b8b71d8b",
          "name": "stringField",
          "type": "string",
          "hidden": true,
          "optional": false,
          "array": false,
          "readonly": false,
          "queryable": true
        },
        {
          "_id": "64affb63b22ee0db653cf294",
          "name": "numberField",
          "type": "number",
          "hidden": false,
          "optional": true,
          "array": false,
          "readonly": false,
          "queryable": true
        },
        {
          "_id": "64b00979a16f8ec037f7e041",
          "name": "booleanField",
          "type": "boolean",
          "hidden": false,
          "optional": true,
          "array": false,
          "readonly": false,
          "queryable": true
        }
      ],
      "indexes": [
        {
          "_id": "64affbcf36fd14263d91945e",
          "name": "field1",
          "order": 1,
          "unique": true,
          "sparse": false
        }
      ]
    }
  ]
}

> {%
  // client.log(response.body._id)
  client.global.set("tableId", response.body._id);
%}
###

// Patch table
PATCH http://localhost:3030/tables/{{tableId}}
Accept: application/json
Content-Type: application/json

{
  "name": "Test",
  "methods": [
    "get",
    "find"
  ],
  "created": true,
  "updated": true,
  "softDelete": true,
  "user": true,
  "fields": [
    {
      "_id": "64affb4f2a4bb338b8b71d8b",
      "name": "stringField",
      "type": "boolean",
      "hidden": true,
      "optional": false,
      "array": false,
      "readonly": false,
      "queryable": true
    },
    {
      "_id": "64affb63b22ee0db653cf294",
      "name": "numberField",
      "type": "number",
      "hidden": false,
      "optional": true,
      "array": false,
      "readonly": false,
      "queryable": true
    },
    {
      "_id": "64b00979a16f8ec037f7e041",
      "name": "booleanField",
      "type": "boolean",
      "hidden": false,
      "optional": true,
      "array": false,
      "readonly": false,
      "queryable": true
    }
  ]
}
###
