// List forms
GET http://localhost:3030/forms
Accept: application/json
Content-Type: application/json
###

// Create forms
POST http://localhost:3030/forms
Accept: application/json
Content-Type: application/json

{
  "list": [
    {
      "_id": "64b410a0a8e639dab4e3e541",
      "name": "Form 1",
      "data": {
        "name": "Bob Cashflow",
        "active": true
      },
      "_fields": [
        {
          "_id": "64b40e66fd77c9b5d159bc6c",
          "_type": "row",
          "name": "row1",
          "_columns": [
            {
              "_id": "64b40e6b4ab865f040a443fb",
              "_type": "col",
              "name": "col1",
              "size": 6,
              "_fields": [
                {
                  "_id": "64b40d6aec6b76cac94a91e3",
                  "_type": "text",
                  "name": "name",
                  "label": "name",
                  "dense": true,
                  "outlined": true
                }
              ]
            },
            {
              "_id": "64b40e7b7600abdf0ec85e13",
              "_type": "col",
              "name": "col2",
              "size": 6,
              "_fields": [
                {
                  "_id": "64b40d708822f84e00862cc9",
                  "_type": "checkbox",
                  "name": "active",
                  "label": "Active?"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

> {%
  // client.log(response.body._id)
  client.global.set("formId", response.body._id);
%}
###

// Patch forms
PATCH http://localhost:3030/forms/{{formId}}
Accept: application/json
Content-Type: application/json

{
  "_id": "{{ formId }}",
  "list": [
    {
      "_id": "64b410a0a8e639dab4e3e541",
      "name": "Form 1",
      "data": {
        "name": "Bob Cashflow",
        "active": true
      },
      "_fields": [
        {
          "_id": "64b40e66fd77c9b5d159bc6c",
          "_type": "row",
          "name": "row1",
          "_columns": [
            {
              "_id": "64b40e6b4ab865f040a443fb",
              "_type": "col",
              "name": "col1",
              "size": 6,
              "_fields": [
                {
                  "_id": "64b40d6aec6b76cac94a91e3",
                  "_type": "text",
                  "name": "name",
                  "label": "name",
                  "dense": true,
                  "outlined": true
                }
              ]
            },
            {
              "_id": "64b40e7b7600abdf0ec85e13",
              "_type": "col",
              "name": "col2",
              "size": 6,
              "_fields": [
                {
                  "_id": "64b40d708822f84e00862cc9",
                  "_type": "checkbox",
                  "name": "active",
                  "label": "Active?"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
###
