// Login
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "strategy": "local",
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("token", response.body.accessToken); %}
###

// List forms
GET http://localhost:3030/forms
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

// Create forms
POST http://localhost:3030/forms
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
}

> {%
  // client.log(response.body._id)
  client.global.set("formId", response.body._id);
%}
###

// Patch forms
PATCH http://localhost:3030/forms/{{formId}}
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "_id": "{{formId}}"
}
###
