// List menus
GET http://localhost:3030/menus
Accept: application/json
Content-Type: application/json
###

// Create menus
POST http://localhost:3030/menus
Accept: application/json
Content-Type: application/json

{
  "list": [
    {
      "label": "Test 1",
      "icon": "mdi-archive-cog",
      "color": "red-3",
      "tabs": [
        {
          "_id": "64b4049c8a7de5f30a638852",
          "label": "Tab 1",
          "icon": "mdi-archive-cog",
          "color": "red-3",
          "formId": "64b410a0a8e639dab4e3e541"
        },
        {
          "_id": "64b404bbc0bab3cd5e013ae0",
          "label": "Tab 2",
          "icon": "mdi-archive-edit",
          "color": "orange-3",
          "formId": "64b410a0a8e639dab4e3e541"
        }
      ]
    }
  ]
}

> {%
  // client.log(response.body._id)
  client.global.set("menuId", response.body._id);
%}
###

// Patch menus
PATCH http://localhost:3030/menus/{{menuId}}
Accept: application/json
Content-Type: application/json

{
}
###
