import { QBtn } from 'quasar'
import { StringEnum, Type } from '@feathersjs/typebox'
import { contentIcon, styleIcon, actionIcon } from '@/shared/icons'
import { TFormComponent } from '@/shared/interfaces/forms'
import { properties, commonProperties, defaultStyleValues } from './common'

export default {
  type: 'button',
  icon: 'mdi-button-pointer',
  label: 'Button',
  component: QBtn,
  schema: properties([
    commonProperties.state,
    commonProperties.size,
    commonProperties.style,
    commonProperties.events,
    Type.Object({
      label: Type.String(),
      color: Type.String({ color: true }),
      textColor: Type.String({ color: true }),
      to: Type.String(),
      target: Type.String(),
      replace: Type.Boolean(),
      loading: Type.Boolean(),
      noCaps: Type.Boolean(),
      noWrap: Type.Boolean(),
      align: StringEnum([
        'left',
        'right',
        'center',
        'around',
        'between',
        'spaced',
      ]),
      icon: Type.String({ icon: true }),
      stack: Type.Boolean(),
      stretch: Type.Boolean(),
      round: Type.Boolean(),
      rounded: Type.Boolean(),
      glossy: Type.Boolean(),
      outline: Type.Boolean(),
      flat: Type.Boolean(),
      push: Type.Boolean(),
      square: Type.Boolean(),
      unelevated: Type.Boolean(),
      fab: Type.Boolean(),
      fabMini: Type.Boolean(),
      click: Type.String({ objectid: true, action: true }),
    }),
  ], false),
  defaultValues: {
    align: 'center',
    flat: true,
    ...defaultStyleValues,
  },
  categories: {
    content: {
      icon: contentIcon,
      names: [
        'name',
        'disable',
        'readonly',
        'label',
        'icon',
        'align',
        'noCaps',
        'noWrap',
        'to',
        'target',
        'replace',
        'loading',
      ],
    },
    style: {
      icon: styleIcon,
      names: [
        'dense',
        'size',
        'color',
        'textColor',
        'stack',
        'stretch',
        'round',
        'rounded',
        'glossy',
        'outline',
        'flat',
        'push',
        'square',
        'unelevated',
        'fab',
        'fabMini',
        'border',
        'padding',
        'margin',
      ],
    },
    action: {
      icon: actionIcon,
      names: [
        'click',
        'focus',
        'blur',
      ],
    },
  },
} as TFormComponent
