import { QDate } from 'quasar'
import { StringEnum, Type } from '@feathersjs/typebox'
import {
  actionIcon, contentIcon, modelIcon, styleIcon,
} from '@/shared/icons'
import { TFormComponent } from '@/shared/interfaces/forms'
import ExType from '@/shared/extypes'
import {
  properties, commonProperties, defaultStyleValues, commonEventArgs, styleNames,
} from './common'

export default {
  type: 'date',
  icon: 'mdi-calendar',
  label: 'components.date.label',
  component: QDate,
  schema: properties([
    commonProperties.state,
    commonProperties.style,
    commonProperties.events,
    Type.Object({
      value: Type.String(),
      landscape: Type.Boolean(),
      outlined: Type.Boolean(),
      yearsInMonthView: Type.Boolean(),
      title: Type.String(),
      subTitle: Type.String(),
      todayBtn: Type.Boolean(),
      minimal: Type.Boolean(),
      mask: Type.String(),
      calendar: StringEnum(['gregorian', 'persian']),
      defaultYearMonth: Type.String(),
      defaultView: StringEnum(['Calendar', 'Months', 'Years']),
      firstDayOfWeek: Type.Number(),
      multiple: Type.Boolean(),
      range: Type.Boolean(),
      emitImmediately: Type.Boolean(),
      navigationMinYearMonth: Type.String(),
      navigationMaxYearMonth: Type.String(),
      noUnset: Type.Boolean(),
      color: ExType.Color({ quasarPalette: true }),
      textColor: ExType.Color({ quasarPalette: true }),
      square: Type.Boolean(),
      flat: Type.Boolean(),
      bordered: Type.Boolean(),
      hideBottomSpace: Type.Boolean(),
      backgroundColor: ExType.Color(),
      navigation: ExType.Action(),
      rangeStart: ExType.Action(),
      rangeEnd: ExType.Action(),
    }),
  ]),
  modelValueField: 'value',
  defaultValues: {
    dense: true,
    outlined: true,
    calendar: 'gregorian',
    defaultView: 'Calendar',
    hideBottomSpace: true,
    ...defaultStyleValues,
  },
  categories: {
    content: {
      icon: contentIcon,
      names: [
        'disable',
        'readonly',
        'title',
        'subTitle',
        'calendar',
        'defaultView',
        'defaultYearMonth',
        'yearsInMonthView',
        'firstDayOfWeek',
        'navigationMinYearMonth',
        'navigationMaxYearMonth',
      ],
    },
    model: {
      icon: modelIcon,
      names: [
        'name',
        'value',
        'field',
        'emitImmediately',
        'noUnset',
        'mask',
        'multiple',
        'range',
      ],
    },
    style: {
      icon: styleIcon,
      names: [
        'dense',
        'todayBtn',
        'landscape',
        'outlined',
        'minimal',
        'color',
        'textColor',
        'square',
        'flat',
        'bordered',
        'hideBottomSpace',
        'backgroundColor',
        ...styleNames,
      ],
    },
    action: {
      icon: actionIcon,
      names: [
        'update',
        'navigation',
        'rangeStart',
        'rangeEnd',
        'focus',
        'blur',
        'keydown',
        'keypress',
        'keyup',
      ],
    },
  },
  eventArgs: {
    ...commonEventArgs,
    navigation: ({ year, month }) => ({ year, month }),
    rangeStart: ({ year, month, day }) => ({ year, month, day }),
    rangeEnd: ({ year, month, day }) => ({ year, month, day }),
  },
} as TFormComponent
