import { Type } from '@feathersjs/typebox'
import { contentIcon, modelIcon, styleIcon } from '@/shared/icons'
import { TFormComponent } from '@/shared/interfaces/forms'
import IconField from '@/features/Fields/components/IconField.vue'
import { properties, commonProperties } from './common'

export default {
  type: 'icon-select',
  icon: 'mdi-form-select',
  label: 'Icon Select',
  component: IconField,
  schema: properties([
    commonProperties.state,
    Type.Object({
      modelValue: Type.String(),
      virtualScrollHorizontal: Type.Boolean(),
      loading: Type.Boolean(),
      clearable: Type.Boolean(),
      tableColspan: Type.Number(),
      noErrorIcon: Type.Boolean(),
      label: Type.String(),
      labelColor: Type.String({ color: true }),
      color: Type.String({ color: true }),
      bgColor: Type.String({ color: true }),
      stackLabel: Type.Boolean(),
      hint: Type.String(),
      hideHint: Type.Boolean(),
      prefix: Type.String(),
      suffix: Type.String(),
      multiple: Type.Boolean(),
      hideSelected: Type.Boolean(),
      maxValues: Type.Number(),
      useChips: Type.Boolean(),
      useInput: Type.Boolean(),
      filled: Type.Boolean(),
      outlined: Type.Boolean(),
      square: Type.Boolean(),
      borderless: Type.Boolean(),
      standout: Type.Boolean(),
      rounded: Type.Boolean(),
      itemAligned: Type.Boolean(),
      hideBottomSpace: Type.Boolean(),
    }),
    commonProperties.style,
  ]),
  defaultValues: {
    dense: true,
    outlined: true,
    emitValue: true,
    useInput: true,
  },
  categories: {
    content: {
      icon: contentIcon,
      names: [
        'name',
        'disable',
        'readonly',
        'label',
        'hint',
        'prefix',
        'suffix',
        'tableColspan',
        'loading',
      ],
    },
    model: {
      icon: modelIcon,
      names: [
        'modelValue',
        'clearable',
        'multiple',
        'emitValue',
        'displayValue',
        'maxValues',
        'useInput',
        'optionLabel',
        'optionValue',
        'optionDisable',
        'options',
      ],
    },
    style: {
      icon: styleIcon,
      names: [
        'dense',
        'labelColor',
        'color',
        'bgColor',
        'stackLabel',
        'hideHint',
        'noErrorIcon',
        'hideSelected',
        'useChips',
        'filled',
        'outlined',
        'square',
        'borderless',
        'standout',
        'rounded',
        'itemAligned',
        'hideBottomSpace',
        'virtualScrollHorizontal',
        'padding',
        'margin',
      ],
    },
  },
} as TFormComponent
