import { QRange } from 'quasar'
import { Type } from '@feathersjs/typebox'
import {
  actionIcon, contentIcon, modelIcon, styleIcon,
} from '@/shared/icons'
import { TFormComponent } from '@/shared/interfaces/forms'
import ExType from '@/shared/extypes'
import {
  properties, commonProperties, sizeString, defaultStyleValues, commonEventArgs, styleNames,
} from './common'

export default {
  type: 'range',
  icon: 'mdi-arrow-left-right',
  label: 'components.range.label',
  component: QRange,
  schema: properties([
    commonProperties.state,
    commonProperties.style,
    commonProperties.events,
    Type.Object({
      modelValue: Type.Object({ min: Type.Number(), max: Type.Number() }),
      min: Type.Number(),
      max: Type.Number(),
      innerMin: Type.Number(),
      innerMax: Type.Number(),
      step: Type.Number(),
      snap: Type.Boolean(),
      labelAlways: Type.Boolean(),
      reverse: Type.Boolean(),
      vertical: Type.Boolean(),
      markers: Type.Union([Type.Boolean(), Type.Number()]),
      markerLabels: Type.Boolean(),
      dragRange: Type.Boolean(),
      dragOnlyRange: Type.Boolean(),
      leftLabelValue: Type.String(),
      rightLabelValue: Type.String(),
      switchLabelSide: Type.Boolean(),
      switchMarkerLabelSide: Type.Boolean(),
      thumbSize: sizeString,
      trackSize: sizeString,
      labelColor: ExType.Color({ quasarPalette: true }),
      labelTextColor: ExType.Color({ quasarPalette: true }),
      trackColor: ExType.Color({ quasarPalette: true }),
      thumbColor: ExType.Color({ quasarPalette: true }),
      selectionColor: ExType.Color({ quasarPalette: true }),
      leftLabelColor: ExType.Color({ quasarPalette: true }),
      leftLabelTextColor: ExType.Color({ quasarPalette: true }),
      rightLabelColor: ExType.Color({ quasarPalette: true }),
      rightLabelTextColor: ExType.Color({ quasarPalette: true }),
      leftThumbColor: ExType.Color({ quasarPalette: true }),
      rightThumbColor: ExType.Color({ quasarPalette: true }),
      change: ExType.Action(),
      pan: ExType.Action(),
    }),
  ]),
  defaultValues: {
    modelValue: { min: 0, max: 0 },
    step: 1,
    snap: true,
    max: 10,
    innerMax: 10,
    labelAlways: true,
    ...defaultStyleValues,
  },
  categories: {
    content: {
      icon: contentIcon,
      names: [
        'disable',
        'readonly',
        'reverse',
        'markers',
      ],
    },
    model: {
      icon: modelIcon,
      names: [
        'name',
        'modelValue',
        'field',
        'min',
        'max',
        'innerMin',
        'innerMax',
        'step',
        'snap',
      ],
    },
    style: {
      icon: styleIcon,
      names: [
        'dense',
        {
          label: 'Colors',
          sectionColor: 'red-1',
          children: [
            'labelColor',
            'labelTextColor',
            'leftLabelColor',
            'leftLabelTextColor',
            'rightLabelColor',
            'rightLabelTextColor',
            'trackColor',
            'selectionColor',
            'thumbColor',
            'leftThumbColor',
            'rightThumbColor',
          ],
        },
        'labelAlways',
        'switchLabelSide',
        'switchMarkerLabelSide',
        'vertical',
        'markerLabels',
        'dragRange',
        'dragOnlyRange',
        'trackSize',
        'thumbSize',
        ...styleNames,
      ],
    },
    action: {
      icon: actionIcon,
      names: [
        'update',
        'change',
        'pan',
        'focus',
        'blur',
        'keydown',
        'keypress',
        'keyup',
      ],
    },
  },
  eventArgs: {
    ...commonEventArgs,
    change: (value) => ({ value }),
    pan: (phase) => ({ phase }),
  },
} as TFormComponent
