import { Type } from '@feathersjs/typebox'
import { schema as ruleSchema } from './rule'
import ExType from '../extypes'

export const ACCESS_LEVEL_READONLY = 0
export const ACCESS_LEVEL_EDIT = 1
export const ACCESS_LEVEL_FULL = -1

export const schema = Type.Object(
  {
    _id: ExType.Id(),
    // target userId
    userId: Type.Optional(ExType.Id()),
    // target email if not registered
    email: ExType.Email(),
    // menuId to share
    menuId: ExType.Id({ service: 'menus' }),
    // rules for tables
    rules: Type.Array(ruleSchema),
    // access level
    accessLevel: Type.Number(),
    // is the share disabled?
    disabled: Type.Optional(Type.Boolean()),
    // the share is only valid from this date
    validFrom: Type.Optional(ExType.Date()),
    // the share is only valid until this time
    validUntil: Type.Optional(ExType.Date()),
    // timestamp the share email was sent
    emailSent: Type.Optional(Type.Number()),
    // user wants the email resent
    emailResend: Type.Optional(Type.Boolean()),
    // when the user shared with clicks the email link (navigate to /share-link/...)
    emailClicked: Type.Optional(Type.Number()),

    // generated by frontend when saving
    menuIds: Type.Array(ExType.Id()),
    formIds: Type.Array(ExType.Id()),
    tableIds: Type.Array(ExType.Id()),
    actionIds: Type.Array(ExType.Id()),
  },
  { $id: 'Share', additionalProperties: false },
)
