export const contentIcon = 'mdi-square-edit-outline'
export const modelIcon = 'mdi-variable'
export const styleIcon = 'mdi-palette-swatch-variant'
export const tableIcon = 'mdi-table'
export const actionIcon = 'mdi-flash'
