export const categories = [
  {
    name: 'string',
    label: 'String',
    icon: 'mdi-format-quote-close',
    children: [
      'str',
      'parse',
      'stringify',
      'format',
      'uppercase',
      'lowercase',
      'camelcase',
      'snakecase',
      'kebabcase',
      'capitalize',
      'pad',
      'padStart',
      'padEnd',
      'startsWith',
      'endsWith',
      'trim',
      'escape',
      'unescape',
      'repeat',
      'split',
      'replace',
      'chr',
      'length',
      'at',
      'append',
      'index',
      'indexLast',
      'compare',
      'normalize',
      'substring',
      'nextNo',
    ],
  },
  {
    name: 'array',
    label: 'Array',
    icon: 'mdi-format-list-group',
    children: [
      'isArray',
      'concat',
      'flat',
      'indexOf',
      'reverse',
      'push',
      'shift',
      'pop',
      'unshift',
      'slice',
      'splice',
      'join',
      'map',
    ],
  },
  {
    name: 'form',
    label: 'Form',
    icon: 'mdi-window-maximize',
    children: [
      'val',
      'doc',
    ],
  },
  {
    name: 'table',
    label: 'Table',
    icon: 'mdi-table',
    children: [
      'field',
      'table',
      'selection',
    ],
  },
  {
    name: 'variables',
    label: 'Variables',
    icon: 'mdi-variable',
    children: [
      'var',
    ],
  },
  {
    name: 'debug',
    label: 'Debug',
    icon: 'mdi-bug',
    children: [
      'log',
      'error',
      'info',
      'warn',
    ],
  },
  {
    name: 'navigation',
    label: 'Navigation',
    icon: 'mdi-navigation-variant',
    children: [
      'route',
      'param',
      'link',
      'menuId',
      'tabId',
      'formId',
      'tableId',
      'domain',
    ],
  },
  {
    name: 'date',
    label: 'Date',
    icon: 'mdi-calendar-month',
    children: [
      'now',
      'date',
      'second',
      'millisecond',
      'minute',
      'hour',
      'day',
      'weekday',
      'month',
      'year',
      'week',
      'dayOfYear',
      'quarter',
      'daysInMonth',
      'dateMax',
      'dateMin',
      'add',
      'subtract',
      'startOf',
      'endOf',
      'relative',
      'diff',
      'before',
      'after',
      'same',
      'sameOrBefore',
      'sameOrAfter',
      'leap',
    ],
  },
  {
    name: 'value',
    label: 'Value',
    icon: 'mdi-variable-box',
    children: [
      '$result',
      'localStorage',
      'isNull',
      'isNil',
      'isUndefined',
      'toString',
    ],
  },
  {
    name: 'math',
    label: 'Math',
    icon: 'mdi-numeric',
    children: [
      'max',
      'min',
      'round',
      'floor',
      'ceil',
      'clamp',
      'inRange',
      'random',
      'get',
      'set',
      'merge',
      'pick',
      'omit',
      'isNaN',
      'isInteger',
      'isFinite',
      'PI',
      'MAX_FLOAT',
      'MAX_INT',
      'parseInt',
      'parseFloat',
      'abs',
      'acos',
      'cos',
      'asin',
      'sin',
      'atan',
      'tan',
      'pow',
      'sign',
      'sqrt',
      'trunc',
      'logarithm',
      'toFixed',
      'toLocale',
    ],
  },
  {
    name: 'object',
    label: 'Object',
    icon: 'mdi-code-json',
    children: [
      'omit',
      'pick',
      'merge',
      'entries',
      'keys',
      'values',
      'has',
    ],
  },
  {
    name: 'system',
    label: 'System',
    icon: 'mdi-domain',
    children: [
      'user',
      'setting',
      'uniqueId',
    ],
  },
]
