// Login
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "strategy": "local",
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("token", response.body.accessToken); %}
###

// List plans
GET http://localhost:3030/plans
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

// Create plan
POST http://localhost:3030/plans
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
}

> {%
  // client.log(response.body._id)
  client.global.set("planId", response.body._id);
%}
###
